### ISSUE TITLE
Job Concurrency Control

### ISSUE THREAD

**Issue by guitarrapc** [guitarrapc/githubactions-lab#158]
How does it work?

https://docs.github.com/en/actions/using-jobs/using-concurrency

```yaml
on:
  push:
    branches:
      - main

jobs:
  job-1:
    runs-on: ubuntu-latest
    concurrency:
      group: example-group
      cancel-in-progress: true
```
