### ISSUE TITLE
Use Kesin11/actions-timeline

### ISSUE THREAD

**Issue by guitarrapc** [guitarrapc/githubactions-lab#159]
https://github.com/Kesin11/actions-timeline

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Register this action before your build step. It will then be executed at the end of the job post-processing.
    - uses: Kesin11/actions-timeline@v2
```
