### ISSUE TITLE
Windows GITHUB_PATH

### ISSUE THREAD

**Issue by guitarrapc** [guitarrapc/githubactions-lab#78]
In my case, GITHUB_PATH for Windows should done on PowerShell, not via CMD. This is strange behaviour and may be I'm misunderstood spec.

> https://github.com/orgs/community/discussions/26380

```yaml
# OK
steps:
  - run: |
      echo "${{github.workspace}}/main/extern/crashpad/breakpad/win/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      echo "ETTERNA_ARCH=${{matrix.cfg.name}}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

# NG
steps:
  - run: |
      echo "${{github.workspace}}/main/extern/crashpad/breakpad/win/" > $env:GITHUB_PATH
      echo "ETTERNA_ARCH=${{matrix.cfg.name}}" > $env:GITHUB_ENV

# NG
steps:
  - run: |
      echo "${{github.workspace}}/main/extern/crashpad/breakpad/win/" > %GITHUB_PATH%
      echo "ETTERNA_ARCH=${{matrix.cfg.name}}" > %GITHUB_ENV%
    shell: cmd
```
